### ISSUE TITLE
Plugin Hub Update Failure - IDs are deprecated

### ISSUE THREAD

**Issue by mcgeer** [mcgeer/WastedBankSpace#43]
Use ComponentID or InterfaceID instead of WidgetInfo or WidgetID
at net.runelite.pluginhub.packager.PluginBuildException.of(PluginBuildException.java:54)
at net.runelite.pluginhub.packager.Plugin.assembleDisplayData(Plugin.java:756)
at net.runelite.pluginhub.packager.Plugin.build(Plugin.java:543)
at net.runelite.pluginhub.packager.Packager.buildPlugin(Packager.java:215)
at net.runelite.pluginhub.packager.Packager.lambda$buildPlugins$0(Packager.java:155)
at java.base/java.lang.Thread.run(Thread.java:829)

Will cut an issue for this and look into it tomorrow

**Comment by mcgeer** [comment]
https://github.com/runelite/plugin-hub/pull/5443

**Comment by mcgeer** [comment]
![image](https://github.com/mcgeer/WastedBankSpace/assets/11418505/da3ca7da-d42d-4d2d-9351-8bfe7e620c78)
